apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.wordpress.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.wordpress.persistence.size }}
