apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: store-orchestrator
  labels:
    app: store-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: store-orchestrator
subjects:
- kind: ServiceAccount
  name: store-orchestrator
  namespace: platform
